### PR TITLE
add docker 1.9 binary

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Where's this binary come from?  Built from source, downloaded, etc?

**Comment by wlan0** [comment]
built from source.

**Comment by ibuildthecloud** [comment]
Can you download from the test URLs?

**Comment by ibuildthecloud** [comment]
https://master.dockerproject.org

**Comment by wlan0** [comment]
downloaded from https://master.dockerproject.org/linux/amd64/docker-1.9.0-dev

**Pull request merged**
